### ISSUE TITLE
User Defined Digits after Decimal

### ISSUE THREAD

**Issue by 10AE0739** [Keith-N/KaN-Gauge#10]
It would be nice to be able to set the desired number of digits after the decimal for each value using the website interface. For example, I’d probably round MAP to whole numbers. I’d also add tenths to the Throttle % to help me troubleshoot throttle body problems.

**Comment by Keith-N** [comment]
Making some updates for this now. I'll try to test this over this weekend and if it looks good I'll upload a new build.

**Comment by Keith-N** [comment]
https://github.com/Keith-N/KaN-Gauge/releases/tag/v1.2.0

A new build is up, 1.2.0
