### ISSUE TITLE
Configure Decimals

### ISSUE THREAD

**Issue by 10AE0739** [Keith-N/KaN-Gauge#11]
I successfully configured MAP KPA to have 0 digits after the decimal point. I tried to do this with Ignition Timing and it works until I turn off the car. When I restart, ignition timing goes back to 2 digits.

**Comment by Keith-N** [comment]
It looks like I missed the ignition timing during saving/restoring user configured settings. I'll get that added.

**Comment by Keith-N** [comment]
https://github.com/Keith-N/KaN-Gauge/commit/11ba70a02594286089ff4cc91962de3bd0544ddb

**Comment by Keith-N** [comment]
@10AE0739 
New build with the update
https://github.com/Keith-N/KaN-Gauge/releases/tag/1.2.1
