### ISSUE TITLE
bin file link broken

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [Keith-N/KaN-Gauge#3]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/82395131/183557637-c9b8eade-a793-4bb5-a0e1-3c4e5a58adc1.png">

**Comment by Keith-N** [comment]
It was linking an old file location. It should now be a usable link to the current location.

**Comment by BeerMoneyMotorsports** [comment]
fixed! thanks.
