### ISSUE TITLE
Fahrenheit Option for Aux Temp 1 and Aux Temp 2

### ISSUE THREAD

**Issue by 10AE0739** [Keith-N/KaN-Gauge#7]
I greatly appreciate the Fahrenheit option for temperatures, but Aux Temp 1 and Aux Temp 2 currently only have Celsius options.

**Comment by Keith-N** [comment]
These were intended to be included. They have been updated and added to the list of selectable sensor values.
commit f9aba0233ba8dcc69aedfa06bed0a6fe532ccfa5
