### ISSUE TITLE
Fuel Trim % Error

### ISSUE THREAD

**Issue by 10AE0739** [Keith-N/KaN-Gauge#8]
Fuel Trim % decimal is wrong. Example, 2.51% shows as 251.00 % on gauge.

**Comment by 10AE0739** [comment]
Further testing shows that the value sometimes shows about 6500 something.

**Comment by Keith-N** [comment]
The fuel trim scaling was not set when it was initially added. 

commit 7a399b21d110f4d4cfadceb2a34ebd7af5825236
